language: python
python:
  - 2.7
  # - 3.3
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pyparsing atlas numpy scipy matplotlib dateutil Pillow statsmodels
install:
  # - pip install git+https://github.com/hobson/pybrain.git@master#egg=pybrain-0.3.3
  # - pip install git+https://github.com/hobson/pug-nlp.git@master#egg=pug-nlp-master
  - python setup.py install
  - pip freeze
script: 
  - "python pybrain/tests/runtests.py"
notifications:
  email:
    - admin@totalgood.com
